src/main/java/hr/btb/hrzzspp/spring/view/FileUploadBean.java
package hr.btb.hrzzspp.spring.view;

import hr.btb.hrzzspp.business.ConstantsEvidencije;
import hr.btb.hrzzspp.jpa.EvFile;
import hr.btb.hrzzspp.jpa.FilePublikacija;
import hr.btb.hrzzspp.jpa.FileRad;
import hr.btb.hrzzspp.jpa.FileRezultat;
import hr.btb.hrzzspp.jpa.FileZnRad;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("session")
public class FileUploadBean {
	
	private static final Logger LOG = LoggerFactory.getLogger(FileUploadBean.class);

	protected UploadedFile newFile;
	protected EvFile evFile;
	protected String fileEntityName = "EvFile";
	protected FileRelatedObjectInterface selectedRow;
	protected String poveznica;
	
	public FileUploadBean clean() {
		this.evFile = null;
		this.selectedRow = null;
		this.newFile = null;
		this.poveznica = null;
		
		return this;
	}

	public void handleFileUpload(FileUploadEvent fileUploadEvent) {
		this.newFile = fileUploadEvent.getFile();
		LOG.debug("... fileUploadEvent: {} ...", fileUploadEvent.getSource());

		if (newFile != null) {
//			PfUtils.info("Datoteka uspješno podignuta.", "Veličina datoteke: "
//					+ newFile.getSize() + " Byte");

			try {
				EvFile evFile = null;
				switch(fileEntityName) {				
				case ConstantsEvidencije.FILE_REZULTAT:
					evFile = new FileRezultat();
					break;
				case ConstantsEvidencije.FILE_RADOVI:
					evFile = new FileRad();
					break;
				case ConstantsEvidencije.FILE_ZN_RADOVI:
					evFile = new FileZnRad();
					break;
				case ConstantsEvidencije.FILE_PUBLIKACIJA:
					evFile = new FilePublikacija();
					break;
				default:
					PfUtils.error("Greška kod kreiranja objekta datoteke!", "Nisam uspio pronaći pravu tablicu za datoteku");
				}
				
				if (evFile != null) {
					evFile.setFileName(newFile.getFileName());
					evFile.setFileSize(newFile.getSize());
					evFile.setFileType(newFile.getContentType());
					evFile.setFileBlob(newFile.getContents());
	
					this.evFile = evFile;
	
					LOG.debug("FILE SIZE: {} | BLOB length: {}", newFile.getSize(),
							newFile.getContents().length);
				}
			} catch (Exception e) {
				PfUtils.error("Greška kod kreiranja novog objekta datoteke!",
						e.toString());
			}
		} else {
			PfUtils.warn("Datoteka nije uspješno učitana!",
					"Veličina datoteke je 0 Byte. Je li to u redu?");
		}
	}
	
	public void markForDelete() {
		selectedRow.setFile(null);
	}

	public UploadedFile getNewFile() {
		return newFile;
	}

	public void setNewFile(UploadedFile newFile) {
		this.newFile = newFile;
	}

	public EvFile getEvFile() {
		return evFile;
	}

	public void setEvFile(EvFile evFile) {
		this.evFile = evFile;
	}

	public String getFileEntityName() {
		return fileEntityName;
	}

	public void setFileEntityName(String fileEntityName) {
		this.fileEntityName = fileEntityName;
	}	
	
	public Object getSelectedRow() {
		return selectedRow;
	}

	public void setSelectedRow(FileRelatedObjectInterface selectedRow) {
		this.selectedRow = selectedRow;
		this.poveznica = selectedRow.getPoveznica();
	}
	
	public String getCurrentFileName() {
		LOG.debug("... getting relevant file name ...");
		if (newFile != null) {
			return newFile.getFileName();

		} else {
			return selectedRow.getFile().getFileName();
		}
	}
	

	public String getPoveznica() {
		return poveznica;
	}

	public void setPoveznica(String poveznica) {
		this.poveznica = poveznica;
	}

	@Override
	public String toString() {
		return String
				.format("FileUploadBean [newFile=%s, evFile=%s, fileEntityName=%s, selectedRow=%s]",
						newFile, evFile, fileEntityName, selectedRow);
	}
	
	
}

src/main/webapp/page_partials/brDocDisertacija.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">


	<h1 style="font-size: 12" align="center">TABLICA 6: Broj
		doktorskih disertacija proizašlih s projekta (NIJE OBVEZNA)</h1>

	<p:separator style="height:7px" />

	<h:form id="form_tablica_brDokDisertacija">

		<p:dataTable value="#{brDocDisertacijaView.fillTable()}"
			var="brojDisertacija" type="ordered" selectionMode="single"
			rowKey="#{brojDisertacija.id}" id="tablica_docDisertacije"
			selection="#{brDocDisertacijaView.odabranaEvDokDisertacije}"
			tableStyleClass="br-dr-disertacija-wrapper">

			<p:column escape="false" headerText="Opcije"
				rendered="#{preventAction.isRendered('OPCIJE')}"
				style="width:4em; align:center;">

				<p:commandButton disabled="#{preventAction.isDisabled('EDIT')}" value=""
					class="ikona-edit" style="buttonNew" rendered="#{preventAction.isRendered('EDIT')}"
					oncomplete="PF('tabl6Dialog_edit').show()"
					update="edit_tabl6Dialog">
					<f:setPropertyActionListener value="#{brojDisertacija}"
						target="#{brDocDisertacijaView.currentRow}" />
				</p:commandButton>

				<p:commandButton value="PRK" rendered="#{preventAction.isRendered('PRK')}"
					oncomplete="PF('prkBDDDialogWidget').show()" class="ikona-prk ikona-prk-pozicija"
					update="prkBDDDialog">
					<f:setPropertyActionListener value="#{brojDisertacija}"
						target="#{brDocDisertacijaView.currentRow}" />
				</p:commandButton>
			</p:column>

			<p:column escape="false"
				headerText="Ukupan broj doktorskih disertacija proizašlih s projekta "
				style="width:10em" sortBy="#{brojDisertacija.brojUkupan}">
				<h:outputText escape="false" value="#{brojDisertacija.brojUkupan}" />
			</p:column>

			<p:column escape="false"
				headerText="Broj doktorskih disertacija čiji su autori doktorandi financirani sredstvima HRZZ-a "
				style="width:10em" sortBy="#{brojDisertacija.brojFinHrzz}">
				<h:outputText escape="false" value="#{brojDisertacija.brojFinHrzz}" />
			</p:column>
			<p:column escape="false"
				headerText="Broj disertacija u suradnji s partnerima izvan znanstvene zajednice"
				style="width:10em" sortBy="#{brojDisertacija.brojIzvanZz}">
				<h:outputText escape="false" value="#{brojDisertacija.brojIzvanZz}" />
			</p:column>

			<p:column escape="false"
				headerText="Broj disertacija izravno implementiranih u gospodarstvo"
				style="width:10em" sortBy="#{brojDisertacija.brojGospodarstvo}">
				<h:outputText escape="false"
					value="#{brojDisertacija.brojGospodarstvo}" />
			</p:column>
			<p:column escape="false"
				headerText="Broj dvojnih doktorskih disertacija " style="width:10em"
				sortBy="#{brojDisertacija.brojDvojnih}">
				<h:outputText escape="false" value="#{brojDisertacija.brojDvojnih}" />
			</p:column>

			<p:column escape="false"
				headerText="Broj objavljenih radova i patenata proizišlih iz doktorskih disertacija "
				style="width:10em" sortBy="#{brojDisertacija.brojRadovaIPatenata}">
				<h:outputText escape="false"
					value="#{brojDisertacija.brojRadovaIPatenata}" />
			</p:column>
			<p:column escape="false"
				headerText="Broj doktorskih disertacija u postupku izdavanja u vidu znanstvenih monografija kod inozemnih izdavača"
				style="width:10em" sortBy="#{brojDisertacija.brojIzdavanje}">
				<h:outputText escape="false"
					value="#{brojDisertacija.brojIzdavanje}" />
			</p:column>

		</p:dataTable>

	</h:form>

	<p:dialog id="edit_tabl6Dialog" header="Broj doktorskih disertacija"
		widgetVar="tabl6Dialog_edit" resizable="false" showEffect="fade"
		hideEffect="explode" closeOnEscape="true" closable="true"
		rendered="true">

		<h:form id="form_edit">
			<p:panel id="edit_panel">

				<p:messages id="msgsView" showDetail="true" />
				<h:panelGrid id="displayView" columns="3" cellpadding="4" border="0">

					<p:outputLabel
						value="Broj doktorskih disertacija čiji su autori doktorandi financirani sredstvima HRZZ-a"
						for="brojFinHrzzView" />
					<p:spinner id="brojFinHrzzView"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.brojFinHrzz}"
						min="0" max="999" style="align:center;" size="5" />
					<p:message for="brojFinHrzzView" display="icon" />

					<p:outputLabel
						value="Broj disertacija u suradnji s partnerima izvan znanstvene zajednice:"
						for="brojIzvanZzView" />
					<p:spinner id="brojIzvanZzView"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.brojIzvanZz}"
						min="0" max="999" style="align:center;" size="5" />
					<p:message for="brojIzvanZzView" display="icon" />

					<p:outputLabel
						value="Broj disertacija izravno implementiranih u gospodarstvo:"
						for="brojGospodarstvoView" />
					<p:spinner id="brojGospodarstvoView"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.brojGospodarstvo}"
						min="0" max="999" style="align:center;" size="5" />
					<p:message for="brojGospodarstvoView" display="icon" />

					<p:outputLabel value="Broj dvojnih doktorskih disertacija:"
						for="brojDvojnihView" />
					<p:spinner id="brojDvojnihView"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.brojDvojnih}"
						min="0" max="999" style="align:center;" size="5" />
					<p:message for="brojDvojnihView" display="icon" />

					<p:outputLabel
						value="Broj objavljenih radova i patenata proizišlih iz doktorskih disertacija:"
						for="brojRadovaIPatenataView" />
					<p:spinner id="brojRadovaIPatenataView"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.brojRadovaIPatenata}"
						min="0" max="999" style="align:center;" size="5" />
					<p:message for="brojRadovaIPatenataView" display="icon" />

					<p:outputLabel
						value="Broj doktorskih disertacija u postupku izdavanja u vidu znanstvenih monografija kod inozemnih izdavača:"
						for="brojIzdavanjeView" />
					<p:spinner id="brojIzdavanjeView"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.brojIzdavanje}"
						min="0" max="999" style="align:center;" size="5" />
					<p:message for="brojIzdavanjeView" display="icon" />

				</h:panelGrid>
			</p:panel>

			<div align="center">
				<br /> <br />
				<p:commandButton disabled="#{!preventAction.periodActive}"
					value="Spremi" style="width:30%"
					action="#{brDocDisertacijaView.update()}"
					oncomplete="setMsgfadeOut('msgsView');"
					update="edit_panel,form_tablica_brDokDisertacija"
					class="bttn-dialog-save" />
				<p:commandButton disabled="#{!preventAction.periodActive}"
					value="Odustani" style="width:30%" onclick="tabl6Dialog.hide();"
					class="bttn-dialog-cancel" partialSubmit="true" />
			</div>
		</h:form>
	</p:dialog>

	<p:dialog id="prkBDDDialog" header="Unošenje statusa" rendered="true"
		widgetVar="prkBDDDialogWidget" resizable="false" showEffect="fade"
		hideEffect="explode" closeOnEscape="true" closable="true">
		<h:form id="prkBDDForm">

			<p:panel id="prkBDDPanel">
				<p:messages id="msgsNew" showDetail="true" />
				<h:panelGrid id="prkBDDPanelGrid" columns="2" cellpadding="4"
					border="0">

					<p:outputLabel for="status" value="Status:" />
					<p:selectOneRadio id="status"
						value="#{brDocDisertacijaView.odabranaEvDokDisertacije.statusPrk}">
						<f:selectItems var="statusPrk"
							value="#{selectOneRadioStatusPrk.statusiPrk}"
							itemValue="#{statusPrk.statusId}"
							itemLabel="#{statusPrk.statusDescription}" />
					</p:selectOneRadio>

				</h:panelGrid>
				
				<p:inputTextarea rows="3" cols="50"
					value="#{brDocDisertacijaView.odabranaEvDokDisertacije.komentarPrk}"
					placeholder="Komentari" />


			</p:panel>
			<div align="center">
				<br />
				
				<p:commandButton value="Spremi" style="width:30%" action="#{brDocDisertacijaView.spremiPRK()}"
					oncomplete="setMsgfadeOut('msgsView');"
					update="prkBDDForm, form_tablica_brDokDisertacija" class="bttn-dialog-save" />

			</div>
		</h:form>
	</p:dialog>

	<script type="text/javascript">
	
		// HOTFIX Sirina retka sa ikonama delete, edit i prk je uvijek takva da ikone stanu jedan kraj druge,
		// umjesto fiksne najbolje da bude auto, a za to treba testirati strukturu i ovisno i prioritetima
		$('table.br-dr-disertacija-wrapper > tbody > tr > td:first-child, ' +
		  'table.br-dr-disertacija-wrapper > thead > tr > th:first-child').css('width', '6em', 'important')
	
	</script>
	
</ui:composition>

src/main/webapp/page_partials/fileUploadFormRow.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">

	<p:outputLabel value="Poveznica ili upload dokumenta:" for="fileView" />
	<p:panel id="fileView" styleClass="file-upload-panel">
		<p:inputText id="poveznica" value="#{fileUploadBean.poveznica}"
			size="50" maxlength="255">
			<f:validateLength maximum="255" />
		</p:inputText>
		<br />
		<p:fileUpload id="fileNew" mode="advanced" auto="true"
			multiple="false"
			fileUploadListener="#{fileUploadBean.handleFileUpload}"
			value="#{fileUploadBean.newFile}" fileLimit="1" label="Dokument"
			uploadLabel="Podizanje..." update="fileView" />
		<h:outputText
			rendered="#{fileUploadBean.selectedRow.file != null || fileUploadBean.evFile != null}"
			value="#{fileUploadBean.currentFileName}" />
		<p:commandLink styleClass="del-link"
			rendered="#{fileUploadBean.selectedRow.file != null || fileUploadBean.evFile != null}"
			action="#{fileUploadBean.markForDelete}" update="@(form)"
			oncomplete="setMsgfadeOut('msgsView');">
			<i class="fa fa-trash-o"></i>
		</p:commandLink>
	</p:panel>
</ui:composition>

src/main/webapp/page_partials/osoblje.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">
	
	<script type="text/javascript">
		
		$(document).ready(function () {
			 
			 $('input.ui-spinner-input').on('input', function(){
					var vrijednost = $(this).val();
					if (vrijednost &lt; 0)
					 $(this).val('0');
				});
		});	
	</script>
	
    <p:growl autoUpdate="true" id="globalMsgs" showDetail="true"
        widgetVar="globalMsgsWidget" life="5000" />

	<h1 style="font-size: 12" align="center">TABLICA 3: Osoblje</h1>
	<p:separator style="height:7px" />
	<div style="font-size: 12">* Podaci iz Tablice 3. i slijedećih
		tablica potrebni su HRZZ-u zbog obveze izvještavanja koju ima prema
		Hrvatskom zavodu za statistiku, Ministarstvu znanosti, obrazovanja i
		sporta i drugim državnim ustanovama.</div>
	<h:form id="osobljeDTForm">

		<p:messages id="msgsView" />
		<div style="font-size: 12">
			Navedite broj osoba koje su sudjelovale u provođenju projekta,
			uključujući i konzultantske osobe:
			<p:spinner id="brojOsoba" disabled="#{!preventAction.periodActive}"
				value="#{osobljeView.brOsoba}"
				min="0" max="999" style="align:center;" size="5"/>
		</div>
		<p:dataTable value="#{osobljeView.osobljeOnProject}" var="row"
			type="ordered" rowKey="#{row.id}" id="osobljeDT" tableStyleClass="tablica-osoblje-wrapper"
			editable="#{preventAction.rendered == true and preventAction.periodActive == true ? true : false}"
			editMode="cell" widgetVar="cellOsoblje">

			<p:ajax event="cellEdit" listener="#{osobljeView.onCellEdit}"
				update=":osobljeDTForm:osobljeDT" />

			<p:column escape="false" headerText="Radno mjesto" style="width:10em"
				sortBy="#{row.radnoMjesto.description}" footerText="Ukupno:">
				<h:outputText escape="false" value="#{row.radnoMjesto.description}" />
			</p:column>

			<p:column escape="false" headerText="Broj žena" style="width:5em"
				sortBy="#{row.brojZena}"
				footerText="#{osobljeView.getBrojTotal('zene')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojZena}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojZena" value="#{row.brojZena}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column escape="false" headerText="Broj muškaraca"
				style="width:5em" sortBy="#{row.brojMuskaraca}"
				footerText="#{osobljeView.getBrojTotal('muskaraci')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojMuskaraca}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojMuskaraca" value="#{row.brojMuskaraca}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column escape="false" style="width:5em"
				sortBy="#{row.brojUPrivSektoru}"
				headerText="Broj zaposlenih u privatnom sektoru"
				footerText="#{osobljeView.getBrojTotal('privatni')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojUPrivSektoru}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojUPrivSektoru" value="#{row.brojUPrivSektoru}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column escape="false" style="width:5em"
				headerText="Broj zaposlenih u javnom sektoru"
				sortBy="#{row.brojUJavSektoru}"
				footerText="#{osobljeView.getBrojTotal('javni')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojUJavSektoru}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojUJavSektoru" value="#{row.brojUJavSektoru}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column escape="false" style="width:5em"
				headerText="Broj zaposlenih u javnim sveučilištima i znanstvenim institutima"
				sortBy="#{row.brojUSveucilistu}"
				footerText="#{osobljeView.getBrojTotal('sveuciliste')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojUSveucilistu}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojUSveucilistu" value="#{row.brojUSveucilistu}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column escape="false" headerText="Broj zaposlenih u inozemstvu"
				style="width:5em" sortBy="#{row.brojUInozemstvu}"
				footerText="#{osobljeView.getBrojTotal('inozemstvo')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojUInozemstvu}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojUInozemstvu" value="#{row.brojUInozemstvu}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<p:column escape="false" headerText="Broj nezaposlenih"
				style="width:5em" sortBy="#{row.brojNezaposlenih}"
				footerText="#{osobljeView.getBrojTotal('nezaposleni')}">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText escape="false" value="#{row.brojNezaposlenih}" />
					</f:facet>
					<f:facet name="input">
						<p:spinner label="brojNezaposlenih" value="#{row.brojNezaposlenih}" min="0" max="999" style="align:center;" size="6"/>
					</f:facet>
				</p:cellEditor>
			</p:column>

			<f:facet name="footer">
				<p:commandButton disabled="#{!preventAction.periodActive}"
					value="SPREMI" icon="ui-icon-save"
					rendered="#{preventAction.rendered}"
					oncomplete="setMsgfadeOut('msgsView'); $('.cmd-hidden-save').click()" />
				<p:commandButton disabled="#{!preventAction.periodActive}"
					value="SPREMI_hidden" class="cmd-hidden-save"
					action="#{osobljeView.save()}" update="osobljeDT" visible="false" />
				<p:commandButton value="PRK" rendered="#{preventAction.isRendered('PRK')}"
					oncomplete="PF('prkOsobljeDialogWidget').show()" update="prkOsobljeDialog">
				</p:commandButton>
			</f:facet>

		</p:dataTable>

	</h:form>
	<p:dialog id="prkOsobljeDialog" header="Unošenje statusa" rendered="true"
		widgetVar="prkOsobljeDialogWidget" resizable="false" showEffect="fade"
		hideEffect="explode" closeOnEscape="true" closable="true">
		<h:form id="prkOsobljeForm">

			<p:panel id="prkOsobljePanel">
				<p:messages id="msgsNew" showDetail="true" />
				<h:panelGrid id="prkOsobljePanelGrid" columns="2" cellpadding="4"
					border="0">

					<p:outputLabel for="status" value="Status:" />
					<p:selectOneRadio id="status"
						value="#{osobljeView.evOsobljeBrOsoba.statusPrk}">
						<f:selectItems var="statusPrk"
							value="#{selectOneRadioStatusPrk.statusiPrk}"
							itemValue="#{statusPrk.statusId}"
							itemLabel="#{statusPrk.statusDescription}" />
					</p:selectOneRadio>

				</h:panelGrid>
				
				<p:inputTextarea rows="3" cols="50"
					value="#{osobljeView.evOsobljeBrOsoba.komentarPrk}"
					placeholder="Komentari" />


			</p:panel>
			<div align="center">
				<br />
				
				<p:commandButton value="Spremi" style="width:30%" action="#{osobljeView.spremiPRK()}"
					oncomplete="setMsgfadeOut('msgsView');"
					update="prkOsobljeForm" class="bttn-dialog-save" />

			</div>
		</h:form>
	</p:dialog>
	
	<script type="text/javascript">


	
	</script>
	
</ui:composition>

src/main/webapp/page_partials/rezultatiEvaluacije.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">
	
	
	<h:form id="rezEvalForm">
		<p:dataTable id="rezEvalTable" value="#{popisEvidencijaView.evalIzvjescaList}"
				var="evalIzvj" rowkey="#{evalIzvj.id}" >
				
			<p:column headerText="Evaluator"  style="width:5em" >
				<h:outputText value="#{evalIzvj.user.userData.name} #{evalIzvj.user.userData.surname}"/>
			</p:column>
			
			<p:column headerText="A" style="width:1em;text-align:center" >
				<h:commandButton class="#{evalIzvj.zavOcjenaA != false ? 'ikona-kvacica' : 'display-none'}"/>
			</p:column>
		
			<p:column headerText="B" style="width:1em;text-align:center">
				<h:commandButton class="#{evalIzvj.zavOcjenaB != false ? 'ikona-kvacica' : 'display-none'}"/>
			</p:column>
			
			<p:column headerText="C" style="width:1em;text-align:center">
				<h:commandButton class="#{evalIzvj.zavOcjenaC != false ? 'ikona-kvacica' : 'display-none'}"/>
			</p:column>
			
			<p:column headerText="D" style="width:1em;text-align:center">
				<h:commandButton class="#{evalIzvj.zavOcjenaD != false ? 'ikona-kvacica' : 'display-none'}"/>
			</p:column>
			
		</p:dataTable>
	</h:form>
	</ui:composition>